import type { ApiEntry, EntryPointShape } from "./types";

// The public API of @nannier/canvas: every export of every package entry point, each
// with what it is and where the docs site documents it. Authored by hand, from the
// source: never derive an entry from a name. `bun run check:api` (tools/api/check.ts)
// fails when an export or a file appears or disappears without an entry here, when a
// kind disagrees with what the TypeScript checker sees, and when a docs claim is false.
//
// `docs` is the export's home page when that page names it: its own component page
// (the reference, the examples, the prop tables), or the guide page or section that
// presents it. A name met only in passing (another component's prop table, an
// ordinary word on a page) is `undocumented`. `internal-by-accident` records what the
// source says about a helper the style hub re-exports wholesale; it deprecates
// nothing, and whether any of them leave the API is the owner's decision.

/** Each subpath of package.json `exports`, by how the gate enumerates it. */
export const entryPoints: Readonly<Record<string, EntryPointShape>> = {
  ".": "module",
  "./styles/*": "files",
  "./package.json": "metadata",
};

/** Every named export of the package entry `.` (src/index.ts), values and types. */
export const publicApi: Readonly<Record<string, ApiEntry>> = {
  // src/atoms
  Autocomplete: { kind: "component", docs: "components/autocomplete" },
  AutocompleteProps: { kind: "type", docs: "components/autocomplete" },
  Avatar: { kind: "component", docs: "components/avatar" },
  AvatarGroup: { kind: "component", docs: "components/avatar" },
  AvatarGroupProps: { kind: "type", docs: "components/avatar" },
  AvatarMenu: { kind: "component", docs: "components/avatar" },
  AvatarMenuProps: { kind: "type", docs: "components/avatar" },
  AvatarProps: { kind: "type", docs: "components/avatar" },
  Badge: { kind: "component", docs: "components/badge" },
  BadgeGroup: { kind: "component", docs: "components/badge" },
  BadgeGroupProps: { kind: "type", docs: "components/badge" },
  BadgeProps: { kind: "type", docs: "components/badge" },
  Breadcrumb: { kind: "component", docs: "components/breadcrumb" },
  BreadcrumbItem: { kind: "part", docs: "undocumented" },
  BreadcrumbItemProps: { kind: "type", docs: "components/breadcrumb" },
  BreadcrumbProps: { kind: "type", docs: "components/breadcrumb" },
  Button: { kind: "component", docs: "components/button" },
  ButtonProps: { kind: "type", docs: "components/button" },
  ButtonGroup: { kind: "component", docs: "components/button-group" },
  ButtonGroupItem: { kind: "type", docs: "components/button-group" },
  ButtonGroupProps: { kind: "type", docs: "components/button-group" },
  Checkbox: { kind: "component", docs: "components/checkbox" },
  CheckboxProps: { kind: "type", docs: "components/checkbox" },
  Chip: { kind: "component", docs: "components/chip" },
  ChipProps: { kind: "type", docs: "components/chip" },
  Container: { kind: "component", docs: "components/container" },
  ContainerProps: { kind: "type", docs: "components/container" },
  containerStyle: { kind: "internal-by-accident", docs: "undocumented" },
  FLUID: { kind: "internal-by-accident", docs: "undocumented" },
  Measure: { kind: "internal-by-accident", docs: "undocumented" },
  measureOf: { kind: "internal-by-accident", docs: "undocumented" },
  Divider: { kind: "component", docs: "components/divider" },
  DividerProps: { kind: "type", docs: "components/divider" },
  Dropdown: { kind: "component", docs: "components/dropdown" },
  DropdownItem: { kind: "type", docs: "components/dropdown" },
  DropdownProps: { kind: "type", docs: "components/dropdown" },
  Emblem: { kind: "component", docs: "components/emblem" },
  EmblemProps: { kind: "type", docs: "components/emblem" },
  Grid: { kind: "component", docs: "components/grid" },
  gridCellWidth: { kind: "internal-by-accident", docs: "undocumented" },
  gridColumns: { kind: "internal-by-accident", docs: "undocumented" },
  GridItem: { kind: "part", docs: "components/grid" },
  GridItemProps: { kind: "type", docs: "components/grid" },
  GridProps: { kind: "type", docs: "components/grid" },
  Icon: { kind: "component", docs: "components/icon" },
  IconName: { kind: "type", docs: "undocumented" },
  IconProps: { kind: "type", docs: "components/icon" },
  Image: { kind: "component", docs: "components/image" },
  ImageProps: { kind: "type", docs: "components/image" },
  Input: { kind: "component", docs: "components/input" },
  InputProps: { kind: "type", docs: "components/input" },
  InputOTP: { kind: "component", docs: "components/input-otp" },
  InputOTPProps: { kind: "type", docs: "components/input-otp" },
  Kbd: { kind: "component", docs: "components/kbd" },
  KbdProps: { kind: "type", docs: "components/kbd" },
  Column: { kind: "component", docs: "components/row-column" },
  FlexProps: { kind: "type", docs: "components/row-column" },
  Row: { kind: "component", docs: "components/row-column" },
  Listbox: { kind: "component", docs: "components/listbox" },
  ListboxItem: { kind: "type", docs: "components/listbox" },
  ListboxProps: { kind: "type", docs: "components/listbox" },
  Pagination: { kind: "component", docs: "components/pagination" },
  PaginationProps: { kind: "type", docs: "components/pagination" },
  Popover: { kind: "component", docs: "components/popover" },
  PopoverProps: { kind: "type", docs: "components/popover" },
  Progress: { kind: "component", docs: "components/progress" },
  ProgressProps: { kind: "type", docs: "components/progress" },
  QRCode: { kind: "component", docs: "components/qrcode" },
  QRCodeProps: { kind: "type", docs: "components/qrcode" },
  Radio: { kind: "component", docs: "components/radio" },
  RadioGroup: { kind: "component", docs: "components/radio" },
  RadioGroupProps: { kind: "type", docs: "components/radio" },
  RadioProps: { kind: "type", docs: "components/radio" },
  Reveal: { kind: "component", docs: "components/reveal" },
  RevealGroup: { kind: "component", docs: "components/reveal" },
  RevealGroupProps: { kind: "type", docs: "components/reveal" },
  RevealProps: { kind: "type", docs: "components/reveal" },
  Select: { kind: "component", docs: "components/select" },
  SelectProps: { kind: "type", docs: "components/select" },
  Skeleton: { kind: "component", docs: "components/skeleton" },
  SkeletonProps: { kind: "type", docs: "components/skeleton" },
  Slider: { kind: "component", docs: "components/slider" },
  SliderProps: { kind: "type", docs: "components/slider" },
  Spinner: { kind: "component", docs: "components/spinner" },
  SpinnerProps: { kind: "type", docs: "components/spinner" },
  Stepper: { kind: "component", docs: "components/stepper" },
  StepperProps: { kind: "type", docs: "components/stepper" },
  Swatch: { kind: "component", docs: "components/swatch" },
  SwatchProps: { kind: "type", docs: "components/swatch" },
  Switch: { kind: "component", docs: "components/switch" },
  SwitchProps: { kind: "type", docs: "components/switch" },
  Textarea: { kind: "component", docs: "components/textarea" },
  TextareaProps: { kind: "type", docs: "components/textarea" },
  Tooltip: { kind: "component", docs: "components/tooltip" },
  TooltipProps: { kind: "type", docs: "components/tooltip" },
  Typography: { kind: "component", docs: "components/typography" },
  TypographyProps: { kind: "type", docs: "components/typography" },
  Video: { kind: "component", docs: "components/video" },
  VideoProps: { kind: "type", docs: "components/video" },
  VideoRadius: { kind: "type", docs: "components/video" },
  VideoSource: { kind: "type", docs: "components/video" },

  // src/charts
  AreaChart: { kind: "component", docs: "components/area-chart" },
  AreaChartProps: { kind: "type", docs: "components/area-chart" },
  BarList: { kind: "component", docs: "components/bar-list" },
  BarListProps: { kind: "type", docs: "components/bar-list" },
  BoxPlot: { kind: "component", docs: "components/box-plot" },
  BoxPlotProps: { kind: "type", docs: "components/box-plot" },
  BoxSample: { kind: "type", docs: "components/box-plot" },
  BulletChart: { kind: "component", docs: "components/bullet-chart" },
  BulletChartProps: { kind: "type", docs: "components/bullet-chart" },
  BulletDatum: { kind: "type", docs: "components/bullet-chart" },
  Candle: { kind: "type", docs: "components/candlestick-chart" },
  CandlestickChart: { kind: "component", docs: "components/candlestick-chart" },
  CandlestickChartProps: { kind: "type", docs: "components/candlestick-chart" },
  Chart: { kind: "component", docs: "components/chart" },
  ChartDatum: { kind: "type", docs: "components/chart" },
  ChartProps: { kind: "type", docs: "components/chart" },
  ComposedChart: { kind: "component", docs: "components/composed-chart" },
  ComposedChartProps: { kind: "type", docs: "components/composed-chart" },
  ComposedSeries: { kind: "type", docs: "components/composed-chart" },
  DepthChart: { kind: "component", docs: "components/depth-chart" },
  DepthChartProps: { kind: "type", docs: "components/depth-chart" },
  FunnelChart: { kind: "component", docs: "components/funnel-chart" },
  FunnelChartProps: { kind: "type", docs: "components/funnel-chart" },
  Gauge: { kind: "component", docs: "components/gauge" },
  GaugeProps: { kind: "type", docs: "components/gauge" },
  GeoMap: { kind: "component", docs: "components/geo-map" },
  GeoMapPoint: { kind: "type", docs: "components/geo-map" },
  GeoMapProps: { kind: "type", docs: "components/geo-map" },
  Heatmap: { kind: "component", docs: "components/heatmap" },
  HeatmapProps: { kind: "type", docs: "components/heatmap" },
  Histogram: { kind: "component", docs: "components/histogram" },
  HistogramProps: { kind: "type", docs: "components/histogram" },
  LineChart: { kind: "component", docs: "components/line-chart" },
  LineChartProps: { kind: "type", docs: "components/line-chart" },
  MetricBreakdown: { kind: "component", docs: "components/metric-breakdown" },
  MetricBreakdownChip: { kind: "type", docs: "components/metric-breakdown" },
  MetricBreakdownProps: { kind: "type", docs: "components/metric-breakdown" },
  PieChart: { kind: "component", docs: "components/pie-chart" },
  PieChartProps: { kind: "type", docs: "components/pie-chart" },
  ProgressRing: { kind: "component", docs: "components/progress-ring" },
  ProgressRingProps: { kind: "type", docs: "components/progress-ring" },
  RadarChart: { kind: "component", docs: "components/radar-chart" },
  RadarChartProps: { kind: "type", docs: "components/radar-chart" },
  RadialBarChart: { kind: "component", docs: "components/radial-bar-chart" },
  RadialBarChartProps: { kind: "type", docs: "components/radial-bar-chart" },
  RangeAreaChart: { kind: "component", docs: "components/range-area-chart" },
  RangeAreaChartProps: { kind: "type", docs: "components/range-area-chart" },
  RangePoint: { kind: "type", docs: "components/range-area-chart" },
  ScatterPlot: { kind: "component", docs: "components/scatter-plot" },
  ScatterPlotProps: { kind: "type", docs: "components/scatter-plot" },
  ScatterPoint: { kind: "type", docs: "undocumented" },
  ScatterSelection: { kind: "type", docs: "components/scatter-plot" },
  ScatterSeries: { kind: "type", docs: "components/scatter-plot" },
  ServiceHealthItem: { kind: "type", docs: "components/service-health-list" },
  ServiceHealthList: { kind: "component", docs: "components/service-health-list" },
  ServiceHealthListProps: { kind: "type", docs: "components/service-health-list" },
  BreakdownRow: { kind: "type", docs: "components/bar-list" },
  ChartSeries: { kind: "type", docs: "components/chart" },
  DepthLevel: { kind: "type", docs: "components/depth-chart" },
  StackedSegment: { kind: "type", docs: "components/pie-chart" },
  UptimePeriod: { kind: "type", docs: "components/uptime-bar" },
  Sparkline: { kind: "component", docs: "components/sparkline" },
  SparklineProps: { kind: "type", docs: "components/sparkline" },
  StackedBar: { kind: "component", docs: "components/stacked-bar" },
  StackedBarProps: { kind: "type", docs: "components/stacked-bar" },
  Treemap: { kind: "component", docs: "components/treemap" },
  TreemapDatum: { kind: "type", docs: "components/treemap" },
  TreemapProps: { kind: "type", docs: "components/treemap" },
  UptimeBar: { kind: "component", docs: "components/uptime-bar" },
  UptimeBarProps: { kind: "type", docs: "components/uptime-bar" },
  WaterfallChart: { kind: "component", docs: "components/waterfall-chart" },
  WaterfallChartProps: { kind: "type", docs: "components/waterfall-chart" },
  WaterfallStep: { kind: "type", docs: "components/waterfall-chart" },

  // src/molecules
  Accordion: { kind: "component", docs: "components/accordion" },
  AccordionItem: { kind: "type", docs: "components/accordion" },
  AccordionProps: { kind: "type", docs: "components/accordion" },
  ActionPanel: { kind: "component", docs: "components/action-panels" },
  ActionPanelProps: { kind: "type", docs: "components/action-panels" },
  Alert: { kind: "component", docs: "components/alert" },
  AlertProps: { kind: "type", docs: "components/alert" },
  AlertDialog: { kind: "component", docs: "components/alert-dialog" },
  AlertDialogProps: { kind: "type", docs: "components/alert-dialog" },
  Card: { kind: "component", docs: "components/card" },
  CardContent: { kind: "part", docs: "components/card" },
  CardDescription: { kind: "part", docs: "undocumented" },
  CardFooter: { kind: "part", docs: "components/card" },
  CardHeader: { kind: "part", docs: "components/card" },
  CardMedia: { kind: "part", docs: "components/card" },
  CardMediaProps: { kind: "type", docs: "components/card" },
  CardProps: { kind: "type", docs: "components/card" },
  CardSectionProps: { kind: "type", docs: "components/card" },
  CardSeparator: { kind: "part", docs: "components/card" },
  CardTextProps: { kind: "type", docs: "components/card" },
  CardTitle: { kind: "part", docs: "components/card" },
  CodeBlock: { kind: "component", docs: "components/code-block" },
  CodeBlockProps: { kind: "type", docs: "components/code-block" },
  CodeBlockTab: { kind: "type", docs: "components/code-block" },
  CodeToken: { kind: "internal-by-accident", docs: "undocumented" },
  syntaxColor: { kind: "internal-by-accident", docs: "undocumented" },
  tokenize: { kind: "internal-by-accident", docs: "undocumented" },
  TokenKind: { kind: "internal-by-accident", docs: "undocumented" },
  Collapsible: { kind: "component", docs: "components/collapsible" },
  CollapsibleProps: { kind: "type", docs: "components/collapsible" },
  DescriptionList: { kind: "component", docs: "components/description-lists" },
  DescriptionListAvatar: { kind: "type", docs: "undocumented" },
  DescriptionListItem: { kind: "type", docs: "components/description-lists" },
  DescriptionListProps: { kind: "type", docs: "components/description-lists" },
  EmptyState: { kind: "component", docs: "components/empty-state" },
  EmptyStateProps: { kind: "type", docs: "components/empty-state" },
  Feed: { kind: "component", docs: "components/feeds" },
  FeedItem: { kind: "type", docs: "components/feeds" },
  FeedProps: { kind: "type", docs: "components/feeds" },
  Field: { kind: "component", docs: "components/field" },
  FieldProps: { kind: "type", docs: "components/field" },
  Form: { kind: "component", docs: "components/form" },
  FormProps: { kind: "type", docs: "components/form" },
  FormSection: { kind: "part", docs: "components/form" },
  FormSectionProps: { kind: "type", docs: "components/form" },
  GridList: { kind: "component", docs: "components/grid-lists" },
  GridListAction: { kind: "type", docs: "undocumented" },
  GridListItem: { kind: "type", docs: "components/grid-lists" },
  GridListProps: { kind: "type", docs: "components/grid-lists" },
  MediaObject: { kind: "component", docs: "components/media-objects" },
  MediaObjectProps: { kind: "type", docs: "components/media-objects" },
  flagOf: { kind: "utility", docs: "undocumented" },
  PHONE_COUNTRIES: { kind: "utility", docs: "components/phone-input" },
  PhoneCountry: { kind: "type", docs: "components/phone-input" },
  PhoneEntryProps: { kind: "type", docs: "components/phone-input" },
  PhoneInput: { kind: "component", docs: "components/phone-input" },
  PhoneInputProps: { kind: "type", docs: "components/phone-input" },
  StackedList: { kind: "component", docs: "components/stacked-lists" },
  StackedListItem: { kind: "type", docs: "components/stacked-lists" },
  StackedListMove: { kind: "type", docs: "components/stacked-lists" },
  StackedListProps: { kind: "type", docs: "components/stacked-lists" },
  StatItem: { kind: "type", docs: "components/stats" },
  Stats: { kind: "component", docs: "components/stats" },
  StatsProps: { kind: "type", docs: "components/stats" },

  // src/organisms
  ActionSheet: { kind: "component", docs: "components/action-sheet" },
  ActionSheetAction: { kind: "type", docs: "components/action-sheet" },
  ActionSheetProps: { kind: "type", docs: "components/action-sheet" },
  applyBoardMove: { kind: "utility", docs: "components/board" },
  Board: { kind: "component", docs: "components/board" },
  BoardColumn: { kind: "type", docs: "components/board" },
  BoardItem: { kind: "type", docs: "components/board" },
  BoardMove: { kind: "type", docs: "components/board" },
  BoardProps: { kind: "type", docs: "components/board" },
  Calendar: { kind: "component", docs: "components/calendar" },
  CalendarProps: { kind: "type", docs: "components/calendar" },
  Carousel: { kind: "component", docs: "components/carousel" },
  CarouselProps: { kind: "type", docs: "components/carousel" },
  Command: { kind: "component", docs: "components/command" },
  CommandGroup: { kind: "type", docs: "components/command" },
  CommandItem: { kind: "type", docs: "components/command" },
  CommandProps: { kind: "type", docs: "components/command" },
  clearStoredDashboardOrder: { kind: "utility", docs: "components/dashboard-grid" },
  DASHBOARD_COLUMNS: { kind: "internal-by-accident", docs: "undocumented" },
  DashboardGrid: { kind: "component", docs: "components/dashboard-grid" },
  DashboardGridProps: { kind: "type", docs: "components/dashboard-grid" },
  DashboardTier: { kind: "internal-by-accident", docs: "undocumented" },
  DashboardWidget: { kind: "type", docs: "components/dashboard-grid" },
  effectiveSpan: { kind: "internal-by-accident", docs: "undocumented" },
  moveWidget: { kind: "internal-by-accident", docs: "undocumented" },
  orderedWidgets: { kind: "internal-by-accident", docs: "undocumented" },
  DataTable: { kind: "component", docs: "components/data-table" },
  DataTableColumn: { kind: "type", docs: "components/data-table" },
  DataTableProps: { kind: "type", docs: "components/data-table" },
  DataTableSort: { kind: "type", docs: "components/data-table" },
  Dialog: { kind: "component", docs: "components/dialog" },
  DialogProps: { kind: "type", docs: "components/dialog" },
  DragDropProvider: { kind: "component", docs: "components/drag-drop" },
  DragDropProviderProps: { kind: "type", docs: "components/drag-drop" },
  Draggable: { kind: "part", docs: "components/drag-drop" },
  DraggableProps: { kind: "type", docs: "components/drag-drop" },
  DragHandle: { kind: "part", docs: "components/drag-drop" },
  DragHandleProps: { kind: "type", docs: "components/drag-drop" },
  DropEvent: { kind: "type", docs: "components/drag-drop" },
  DropZone: { kind: "part", docs: "components/drag-drop" },
  DropZoneProps: { kind: "type", docs: "components/drag-drop" },
  Drawer: { kind: "component", docs: "components/drawer" },
  DrawerProps: { kind: "type", docs: "components/drawer" },
  FilterGroup: { kind: "type", docs: "components/filter-panel" },
  FilterOption: { kind: "type", docs: "undocumented" },
  FilterPanel: { kind: "component", docs: "components/filter-panel" },
  FilterPanelProps: { kind: "type", docs: "components/filter-panel" },
  Navbar: { kind: "component", docs: "components/navbars" },
  NavbarProps: { kind: "type", docs: "components/navbars" },
  RowMenu: { kind: "component", docs: "components/row-menu" },
  RowMenuItem: { kind: "type", docs: "components/row-menu" },
  RowMenuProps: { kind: "type", docs: "components/row-menu" },
  Sidebar: { kind: "component", docs: "components/sidebar" },
  SidebarItem: { kind: "type", docs: "components/sidebar" },
  SidebarProps: { kind: "type", docs: "components/sidebar" },
  SidebarSection: { kind: "type", docs: "components/sidebar" },
  Step: { kind: "type", docs: "components/steps" },
  Steps: { kind: "component", docs: "components/steps" },
  StepsProps: { kind: "type", docs: "components/steps" },
  TabBar: { kind: "component", docs: "components/tab-bar" },
  TabBarItem: { kind: "type", docs: "components/tab-bar" },
  TabBarProps: { kind: "type", docs: "components/tab-bar" },
  TabItem: { kind: "type", docs: "components/tabs" },
  Tabs: { kind: "component", docs: "components/tabs" },
  TabsProps: { kind: "type", docs: "components/tabs" },
  Toast: { kind: "component", docs: "components/toast" },
  ToastAction: { kind: "type", docs: "components/toast" },
  ToastHandle: { kind: "type", docs: "undocumented" },
  ToastOptions: { kind: "type", docs: "undocumented" },
  ToastProps: { kind: "type", docs: "components/toast" },
  ToastProvider: { kind: "part", docs: "components/toast" },
  useToast: { kind: "hook", docs: "components/toast" },

  // src/style/a11y-preferences.ts
  useIncreasedContrast: { kind: "hook", docs: "undocumented" },
  useReducedTransparency: { kind: "hook", docs: "undocumented" },

  // src/style/active-indicator.ts
  activeIndicator: { kind: "internal-by-accident", docs: "undocumented" },
  ActiveIndicatorOptions: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/anchored-overlay.tsx
  AnchoredOverlay: { kind: "internal-by-accident", docs: "undocumented" },
  AnchoredOverlayProps: { kind: "internal-by-accident", docs: "undocumented" },
  placeOverlay: { kind: "internal-by-accident", docs: "undocumented" },
  useOverlayAnchor: { kind: "internal-by-accident", docs: "undocumented" },
  useOverlaySide: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/color.ts
  alpha: { kind: "utility", docs: "integration", section: "Package exports" },
  channelsOf: { kind: "utility", docs: "undocumented" },
  composite: { kind: "utility", docs: "undocumented" },
  contrastRatio: { kind: "utility", docs: "undocumented" },
  inkOn: { kind: "utility", docs: "undocumented" },
  mixOklab: { kind: "utility", docs: "undocumented" },
  relativeLuminance: { kind: "utility", docs: "undocumented" },

  // src/style/container.ts
  ContainerBreakpoint: { kind: "type", docs: "undocumented" },
  ContainerBreakpointOptions: { kind: "type", docs: "undocumented" },
  containerProbe: { kind: "internal-by-accident", docs: "undocumented" },
  MeasuredWidth: { kind: "type", docs: "undocumented" },
  useContainerBreakpoint: { kind: "hook", docs: "undocumented" },
  useContainerWidth: { kind: "hook", docs: "undocumented" },
  useMeasuredWidth: { kind: "hook", docs: "undocumented" },

  // src/style/dev-warn.ts
  devWarn: { kind: "internal-by-accident", docs: "undocumented" },
  resetDevWarnings: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/entrance.tsx
  Entrance: { kind: "internal-by-accident", docs: "undocumented" },
  EntranceProps: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/floating-label.tsx
  FloatingLabel: { kind: "internal-by-accident", docs: "undocumented" },
  FloatingLabelStyles: { kind: "internal-by-accident", docs: "undocumented" },
  HIDDEN_FROM_A11Y: { kind: "internal-by-accident", docs: "undocumented" },
  LabelContent: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/focus-reset.ts
  FOCUS_RESET: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/fonts.ts
  FontFaces: { kind: "type", docs: "undocumented" },
  FontWeightKey: { kind: "type", docs: "undocumented" },
  ResolvedFace: { kind: "internal-by-accident", docs: "undocumented" },
  resolveFontFace: { kind: "internal-by-accident", docs: "undocumented" },
  ThemeFonts: { kind: "type", docs: "undocumented" },
  typeface: { kind: "token", docs: "undocumented" },
  weightKey: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/gesture-surface.ts
  GESTURE_SURFACE: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/glass-fill.ts
  innerFill: { kind: "internal-by-accident", docs: "undocumented" },
  InnerFillRole: { kind: "internal-by-accident", docs: "undocumented" },
  InnerFillStrength: { kind: "internal-by-accident", docs: "undocumented" },
  inverseDenseTint: { kind: "internal-by-accident", docs: "undocumented" },
  isGlass: { kind: "internal-by-accident", docs: "undocumented" },
  withInnerFill: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/glass-surface/glass-pane.tsx
  GlassPane: { kind: "internal-by-accident", docs: "theming", section: "Glass Surface" },
  GlassPaneProps: { kind: "internal-by-accident", docs: "undocumented" },
  PANE_SIBLING_INPUT: { kind: "internal-by-accident", docs: "undocumented" },
  paneStyle: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/glass-surface/glass-surface.shared.tsx
  GlassModalBlurTarget: { kind: "component", docs: "undocumented" },

  // src/style/glass-surface/glass-surface.tsx
  GlassSurface: { kind: "internal-by-accident", docs: "theming", section: "Glass Surface" },

  // src/style/glass-surface/liquid-glass.ts
  liquidGlassAvailable: { kind: "utility", docs: "patterns/glass" },

  // src/style/loop.tsx
  createLoopChannel: { kind: "internal-by-accident", docs: "undocumented" },
  LoopChannel: { kind: "internal-by-accident", docs: "undocumented" },
  LoopChannelOptions: { kind: "internal-by-accident", docs: "undocumented" },
  LoopChannelState: { kind: "internal-by-accident", docs: "undocumented" },
  LoopTrack: { kind: "internal-by-accident", docs: "undocumented" },
  LoopView: { kind: "internal-by-accident", docs: "undocumented" },
  LoopViewProps: { kind: "internal-by-accident", docs: "undocumented" },
  trackAt: { kind: "internal-by-accident", docs: "undocumented" },
  trackSamples: { kind: "internal-by-accident", docs: "undocumented" },
  trackValueAt: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/mono.ts
  MONO_FONT: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/motion.ts
  enableAndroidLayoutAnimations: { kind: "internal-by-accident", docs: "undocumented" },
  holdThen: { kind: "internal-by-accident", docs: "undocumented" },
  keyframes: { kind: "internal-by-accident", docs: "undocumented" },
  supportsNativeDriver: { kind: "internal-by-accident", docs: "undocumented" },
  thereAndBack: { kind: "internal-by-accident", docs: "undocumented" },
  useReducedMotion: { kind: "hook", docs: "undocumented" },

  // src/style/numerals.ts
  tabularNums: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/pointer.ts
  useHoverCapable: { kind: "hook", docs: "patterns/responsive" },
  usePointerCoarse: { kind: "hook", docs: "patterns/responsive" },

  // src/style/portal.tsx
  insetOverlayBounds: { kind: "internal-by-accident", docs: "undocumented" },
  intersectOverlayBounds: { kind: "internal-by-accident", docs: "undocumented" },
  OverlayBounds: { kind: "internal-by-accident", docs: "undocumented" },
  OverlayHost: { kind: "internal-by-accident", docs: "undocumented" },
  OverlayProvider: { kind: "component", docs: "components/dialog" },
  OverlayProviderProps: { kind: "type", docs: "undocumented" },
  OverlayViewportInsets: { kind: "type", docs: "undocumented" },
  Portal: { kind: "internal-by-accident", docs: "undocumented" },
  PortalProps: { kind: "internal-by-accident", docs: "undocumented" },
  useOverlayHost: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/pressable.tsx
  Pressable: { kind: "component", docs: "components/pressable" },

  // src/style/responsive.tsx
  BreakpointOverride: { kind: "component", docs: "undocumented" },
  FormFactor: { kind: "type", docs: "undocumented" },
  formFactor: { kind: "utility", docs: "undocumented" },
  Responsive: { kind: "type", docs: "undocumented" },
  responsive: { kind: "utility", docs: "undocumented" },
  SsrBreakpointContext: { kind: "internal-by-accident", docs: "undocumented" },
  useBreakpoint: { kind: "hook", docs: "patterns/responsive" },
  useFormFactor: { kind: "hook", docs: "patterns/responsive" },
  useResponsive: { kind: "hook", docs: "patterns/responsive" },

  // src/style/ripple-clip.tsx
  cornerRadii: { kind: "internal-by-accident", docs: "undocumented" },
  RippleClip: { kind: "internal-by-accident", docs: "undocumented" },
  RippleClipProps: { kind: "internal-by-accident", docs: "undocumented" },
  rippleClipWrapperStyle: { kind: "internal-by-accident", docs: "undocumented" },
  splitElevation: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/ripple.ts
  controlRipple: { kind: "internal-by-accident", docs: "undocumented" },
  platformDisabledDim: { kind: "internal-by-accident", docs: "undocumented" },
  pressDim: { kind: "internal-by-accident", docs: "undocumented" },
  rippleClip: { kind: "internal-by-accident", docs: "undocumented" },
  surfaceRipple: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/rtl.ts
  isRTL: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/shadow.ts
  customShadow: { kind: "internal-by-accident", docs: "undocumented" },
  shadow: { kind: "utility", docs: "tokens/spacing" },
  ShadowLevel: { kind: "type", docs: "undocumented" },

  // src/style/sizing.ts
  CELL_AXIS: { kind: "internal-by-accident", docs: "undocumented" },
  clampSpan: { kind: "internal-by-accident", docs: "undocumented" },
  columnAxis: { kind: "internal-by-accident", docs: "undocumented" },
  FILL: { kind: "internal-by-accident", docs: "undocumented" },
  FillOptions: { kind: "internal-by-accident", docs: "undocumented" },
  GRID_CELL_AXIS: { kind: "internal-by-accident", docs: "undocumented" },
  GRID_COLUMNS: { kind: "internal-by-accident", docs: "undocumented" },
  HUG_IN_STRETCH_COLUMN: { kind: "internal-by-accident", docs: "undocumented" },
  layoutAxis: { kind: "internal-by-accident", docs: "undocumented" },
  LayoutAxis: { kind: "internal-by-accident", docs: "undocumented" },
  LayoutAxisProvider: { kind: "internal-by-accident", docs: "undocumented" },
  LayoutStyle: { kind: "type", docs: "undocumented" },
  MeasureProps: { kind: "type", docs: "undocumented" },
  measureStyle: { kind: "internal-by-accident", docs: "undocumented" },
  ROW_AXIS: { kind: "internal-by-accident", docs: "undocumented" },
  SizingKey: { kind: "type", docs: "undocumented" },
  spanWidth: { kind: "internal-by-accident", docs: "undocumented" },
  stepOf: { kind: "internal-by-accident", docs: "undocumented" },
  useFillStyle: { kind: "internal-by-accident", docs: "undocumented" },
  useHugStyle: { kind: "internal-by-accident", docs: "undocumented" },
  useLayoutAxis: { kind: "internal-by-accident", docs: "undocumented" },
  useMeasureStyle: { kind: "internal-by-accident", docs: "undocumented" },
  useSizing: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/status-hue.ts
  HUE_WASH: { kind: "deprecated-alias", docs: "undocumented", replacement: "statusColors" },
  Hue: { kind: "type", docs: "undocumented" },
  statusHues: { kind: "token", docs: "tokens/colors" },
  StatusTone: { kind: "type", docs: "undocumented" },

  // src/style/status.ts
  StatusColors: { kind: "type", docs: "undocumented" },
  statusColors: { kind: "utility", docs: "undocumented" },
  StatusColorTone: { kind: "type", docs: "undocumented" },

  // src/style/text.tsx
  fontStyle: { kind: "internal-by-accident", docs: "undocumented" },
  Text: { kind: "component", docs: "components/text" },
  TextInput: { kind: "component", docs: "components/text-input" },

  // src/style/theme.tsx
  Surface: { kind: "type", docs: "undocumented" },
  ThemeProvider: { kind: "component", docs: "theming", section: "Native (ThemeProvider)" },
  ThemeProviderProps: { kind: "type", docs: "undocumented" },
  ThemeTokenOverrides: { kind: "type", docs: "undocumented" },
  ThemeValue: { kind: "type", docs: "undocumented" },
  useTheme: { kind: "hook", docs: "theming", section: "Native (ThemeProvider)" },

  // src/style/tokens.ts
  baseColors: { kind: "token", docs: "undocumented" },
  brandColors: { kind: "deprecated-alias", docs: "undocumented" },
  BrandColors: { kind: "type", docs: "undocumented" },
  BreakpointKey: { kind: "type", docs: "undocumented" },
  breakpoints: { kind: "token", docs: "patterns/responsive" },
  colorsByScheme: { kind: "token", docs: "undocumented" },
  ColorScheme: { kind: "type", docs: "undocumented" },
  colorsFor: { kind: "utility", docs: "theming", section: "Palettes" },
  ColorTokens: { kind: "type", docs: "undocumented" },
  darkColors: { kind: "token", docs: "tokens/colors" },
  darkGlass: { kind: "token", docs: "undocumented" },
  fontSize: { kind: "token", docs: "undocumented" },
  fontWeight: { kind: "token", docs: "undocumented" },
  glassByScheme: { kind: "token", docs: "tokens/colors" },
  GlassTokens: { kind: "type", docs: "undocumented" },
  letterSpacing: { kind: "token", docs: "undocumented" },
  lightColors: { kind: "token", docs: "tokens/colors" },
  lightGlass: { kind: "token", docs: "undocumented" },
  lineHeight: { kind: "token", docs: "undocumented" },
  mintColors: { kind: "token", docs: "tokens/colors" },
  palette: { kind: "token", docs: "tokens/colors" },
  Palette: { kind: "type", docs: "undocumented" },
  PlatformKey: { kind: "type", docs: "undocumented" },
  radius: { kind: "token", docs: "tokens/spacing" },
  shape: { kind: "token", docs: "tokens/spacing" },
  ShapeTokens: { kind: "type", docs: "undocumented" },
  spacing: { kind: "token", docs: "tokens/spacing" },
  WidthKey: { kind: "type", docs: "undocumented" },
  widths: { kind: "token", docs: "undocumented" },

  // src/style/touch-target-seed.ts
  MinTargetOptions: { kind: "internal-by-accident", docs: "undocumented" },
  minTargetSlop: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/touch-target.ts
  platformMinTarget: { kind: "internal-by-accident", docs: "undocumented" },
  TOUCH_TARGET: { kind: "internal-by-accident", docs: "undocumented" },
  TouchTargetSkin: { kind: "internal-by-accident", docs: "undocumented" },
  useMinTargetSlop: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-controllable-state.ts
  useControllableState: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-dialog-focus.ts
  useDialogFocus: { kind: "internal-by-accident", docs: "undocumented" },
  usePopoverFocus: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-escape-key.ts
  useEscapeKey: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-hardware-back.ts
  useHardwareBack: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-roving-focus.ts
  RovingFocusOptions: { kind: "internal-by-accident", docs: "undocumented" },
  RovingItemProps: { kind: "internal-by-accident", docs: "undocumented" },
  useRovingFocus: { kind: "internal-by-accident", docs: "undocumented" },

  // src/style/use-wheel.ts
  normalizeWheelDelta: { kind: "internal-by-accident", docs: "undocumented" },
  useWheel: { kind: "internal-by-accident", docs: "undocumented" },
  WheelGesture: { kind: "internal-by-accident", docs: "undocumented" },

  // src/theme.ts
  Density: { kind: "type", docs: "undocumented" },
  getDensity: { kind: "utility", docs: "theming", section: "Density" },
  getPalette: { kind: "utility", docs: "theming", section: "Palettes" },
  getSurface: { kind: "utility", docs: "theming", section: "Glass Surface" },
  getTheme: { kind: "utility", docs: "theming", section: "Light / Dark Mode" },
  setDensity: { kind: "utility", docs: "theming", section: "Density" },
  setPalette: { kind: "utility", docs: "theming", section: "Palettes" },
  setSurface: { kind: "utility", docs: "theming", section: "Glass Surface" },
  setTheme: { kind: "utility", docs: "theming", section: "Light / Dark Mode" },
  Theme: { kind: "type", docs: "undocumented" },
  toggleTheme: { kind: "utility", docs: "theming", section: "Light / Dark Mode" },

  // src/tokens.ts
  hsl: { kind: "utility", docs: "integration", section: "Reading tokens (web)" },
  token: { kind: "utility", docs: "integration", section: "Reading tokens (web)" },

  // react-native, re-exported by src/style/primitives.ts
  ImageStyle: { kind: "type", docs: "undocumented" },
  LayoutChangeEvent: { kind: "type", docs: "undocumented" },
  NativeScrollEvent: { kind: "type", docs: "undocumented" },
  NativeSyntheticEvent: { kind: "type", docs: "undocumented" },
  PressableProps: { kind: "type", docs: "undocumented" },
  PressableStateCallbackType: { kind: "type", docs: "undocumented" },
  ScrollView: { kind: "component", docs: "components/scroll-view" },
  ScrollViewProps: { kind: "type", docs: "undocumented" },
  StyleProp: { kind: "type", docs: "undocumented" },
  StyleSheet: { kind: "internal-by-accident", docs: "undocumented" },
  TextInputProps: { kind: "type", docs: "undocumented" },
  TextProps: { kind: "type", docs: "undocumented" },
  TextStyle: { kind: "type", docs: "undocumented" },
  useWindowDimensions: { kind: "internal-by-accident", docs: "undocumented" },
  View: { kind: "component", docs: "components/view" },
  ViewProps: { kind: "type", docs: "undocumented" },
  ViewStyle: { kind: "type", docs: "undocumented" },
};

/** Every file the `./styles/*` entry point reaches, by repo-relative path. */
export const files: Readonly<Record<string, ApiEntry>> = {
  // The supported CSS entry: the web token hand-off, one file to link.
  "styles/canvas.css": { kind: "token", docs: "integration", section: "Package exports" },
  // The per-concern files canvas.css imports. Each is reachable on its own through the
  // wildcard, and no page names one as an entry point.
  "styles/tokens/base.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/colors.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/density.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/motion.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/palette.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/platforms.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/radius.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/shadows.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/spacing.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/surface.css": { kind: "part", docs: "undocumented" },
  "styles/tokens/typography.css": { kind: "part", docs: "undocumented" },
};
