/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/candlestick-chart/candlestick-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { CandlestickChart } = scope;
  return (
<CandlestickChart
  compact
  labels={["D1", "D2", "D3", "D4", "D5", "D6"]}
  candles={[
    { open: 63.5, high: 63.5, low: 63.5, close: 63.5 },
    { open: 63.9, high: 63.9, low: 63.9, close: 63.9 },
    { open: 63.6, high: 63.6, low: 63.6, close: 63.6 },
    { open: 64.2, high: 64.2, low: 64.2, close: 64.2 },
    { open: 64.4, high: 64.4, low: 64.4, close: 64.4 },
    { open: 65.1, high: 65.1, low: 65.1, close: 65.1 }
  ]}
/>
  );
}
