/*
 * Menu-glyph raster generator (run with `bun run raster:gen`).
 *
 * The docs' native iOS navigation menu is a real UIMenu. A UIMenu item icon accepts only
 * an SF Symbol or a UIImage — never a live <Icon> (react-native-svg) or any vector — so to
 * show the SAME lucide glyphs the web sidebar and Android drawer render, each glyph is
 * baked to a tinted PNG here and handed to the menu as an image source
 * (docs/src/shell/native-header.tsx passes `icon: { type: "image", tinted: true }`, which
 * iOS renders as a template tinted to the menu label color).
 *
 * The glyph geometry is read from the kit's OWN generated vector data
 * (src/atoms/icon/icon.glyphs.ts `ICONS`), the exact source the sidebars draw, so a menu
 * glyph is pixel-identical to its sidebar counterpart and immune to lucide filename/alias
 * drift. Which glyphs to bake comes from `menuGlyphNames()` (docs/src/data/nav.ts), the
 * single source of truth shared with the coverage gate below.
 *
 * Emits, into docs/:
 *   assets/images/menu-glyphs/<name>.png  (+ @2x, @3x)   the bundled rasters
 *   src/core/glyph-rasters.ts             a static `glyph -> require(png)` map
 *
 * `--check` (the pre-push / CI gate) writes nothing: it asserts every menu glyph has a map
 * entry AND its three density PNGs exist, and throws naming any gap. It is a COVERAGE check,
 * not a byte-for-byte PNG check — sharp/libvips output can differ across macOS and CI Linux,
 * and the sibling favicon raster (tools/favicongen) has no gate for the same reason.
 *
 * When bumping the `sharp` devDependency, rerun `bun run raster:gen` and commit any PNG
 * byte changes alongside the bump, so the committed rasters stay in step with the encoder.
 */
import { writeFileSync, readFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, relative } from "node:path";
import sharp from "sharp";
import { ICONS, type Shape } from "../../src/atoms/icon/icon.glyphs.ts";
import { ICON_STROKE_WIDTH } from "../../src/atoms/icon/icon.stroke.ts";
import { menuGlyphNames } from "../../docs/src/data/nav.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../..");
const PNG_DIR = resolve(repo, "docs/assets/images/menu-glyphs");
const MAP_FILE = resolve(repo, "docs/src/core/glyph-rasters.ts");
const rel = (f: string) => relative(repo, f);

const CHECK = process.argv.includes("--check");

// Render densities. Metro resolves `<name>@2x`/`@3x` by device PixelRatio from the 1x
// require, so all three ship and the base name is the required one.
const DENSITIES: { suffix: string; size: number }[] = [
  { suffix: "", size: 24 },
  { suffix: "@2x", size: 48 },
  { suffix: "@3x", size: 72 },
];

// Build one glyph's SVG from its Shape[] using the Icon component's exact presentation
// attributes (src/atoms/icon/icon.shared.tsx Glyph/renderShape): 24-unit viewBox, no fill
// by default, 1.75 stroke, round caps/joins. A `fill` shape fills with the stroke color
// (Lucide `fill="currentColor"`). Stroke is solid black; the PNG ships as a template, so
// iOS tints it and only the alpha channel matters.
const STROKE = "#000";
function shapeSvg(sh: Shape): string {
  const fill = sh.fill ? ` fill="${STROKE}"` : "";
  switch (sh.t) {
    case "path":
      return `<path d="${sh.d}"${fill}/>`;
    case "circle":
      return `<circle cx="${sh.cx}" cy="${sh.cy}" r="${sh.r}"${fill}/>`;
    case "line":
      return `<line x1="${sh.x1}" y1="${sh.y1}" x2="${sh.x2}" y2="${sh.y2}"/>`;
    case "polyline":
      return `<polyline points="${sh.points}"${fill}/>`;
    case "polygon":
      return `<polygon points="${sh.points}"${fill}/>`;
    case "rect":
      return `<rect x="${sh.x}" y="${sh.y}" width="${sh.width}" height="${sh.height}"${sh.rx != null ? ` rx="${sh.rx}"` : ""}${sh.ry != null ? ` ry="${sh.ry}"` : ""}${fill}/>`;
    case "ellipse":
      return `<ellipse cx="${sh.cx}" cy="${sh.cy}" rx="${sh.rx}" ry="${sh.ry}"${fill}/>`;
  }
}
function glyphSvg(shapes: Shape[], size: number): string {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" ` +
    `fill="none" stroke="${STROKE}" stroke-width="${ICON_STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round">` +
    shapes.map(shapeSvg).join("") +
    `</svg>`
  );
}

const GENERATED_HEADER =
  "/* @generated by tools/rastergen — DO NOT EDIT. Run `bun run raster:gen`. */\n" +
  "// Static `menu glyph -> bundled PNG module` map for the native iOS navigation menu.\n" +
  "// The glyphs come from docs/src/data/nav.ts menuGlyphNames(); regenerate after changing\n" +
  "// a nav icon. Keyed by the kit Icon glyph key (camelCase), same as the sidebar rows.\n\n";

function renderMap(names: string[]): string {
  const lines = names
    .map((n) => `  ${n}: require("../../assets/images/menu-glyphs/${n}.png"),`)
    .join("\n");
  return (
    GENERATED_HEADER +
    "export const GLYPH_RASTERS: Record<string, number> = {\n" +
    lines +
    "\n};\n"
  );
}

const names = menuGlyphNames();
const missingGlyphs = names.filter((n) => !ICONS[n]);
if (missingGlyphs.length) {
  // A nav icon that the kit does not ship: fail loud rather than bake a blank.
  console.error(`FATAL: no ICONS glyph for: ${missingGlyphs.join(", ")}`);
  process.exit(1);
}

const pngPath = (name: string, suffix: string) => resolve(PNG_DIR, `${name}${suffix}.png`);

if (CHECK) {
  const drift: string[] = [];
  const wanted = renderMap(names);
  const actual = existsSync(MAP_FILE) ? readFileSync(MAP_FILE, "utf8") : null;
  if (actual !== wanted) drift.push(`${rel(MAP_FILE)} (${actual === null ? "never generated" : "stale"})`);
  for (const n of names) {
    for (const d of DENSITIES) {
      const p = pngPath(n, d.suffix);
      if (!existsSync(p)) drift.push(`${rel(p)} (missing raster)`);
    }
  }
  if (drift.length) {
    throw new Error(
      `raster:gen --check found ${drift.length} menu-glyph raster(s) out of sync. ` +
        `Run \`bun run raster:gen\` and commit the result:\n${drift.map((d) => `    ${d}`).join("\n")}`,
    );
  }
  console.log(`raster:gen --check verified ${names.length} menu glyphs; rasters in sync.`);
} else {
  mkdirSync(PNG_DIR, { recursive: true });
  for (const n of names) {
    for (const d of DENSITIES) {
      const buf = await sharp(Buffer.from(glyphSvg(ICONS[n], d.size))).png().toBuffer();
      writeFileSync(pngPath(n, d.suffix), buf);
    }
  }
  const map = renderMap(names);
  // writeFileIfChanged: leave the map's mtime untouched on a no-op run (Metro keys off it).
  if (!existsSync(MAP_FILE) || readFileSync(MAP_FILE, "utf8") !== map) writeFileSync(MAP_FILE, map);
  console.log(`raster:gen — ${names.length} menu glyphs x ${DENSITIES.length} densities -> ${rel(PNG_DIR)}; map -> ${rel(MAP_FILE)}`);
}
