/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/area-chart/area-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AreaChart } = scope;
  return (
<AreaChart
  stacked
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  series={[
    { label: "Conversion rate", values: [3.1, 3.4, 3.2, 3.8, 4.0, 4.2] },
    { label: "Bounce rate", values: [41, 39, 40, 37, 36, 35] },
    { label: "Churn rate", values: [2.4, 2.2, 2.5, 2.1, 2.0, 1.9] }
  ]}
/>
  );
}
