/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/charts/area-chart/area-chart.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { AreaChart } = scope;
  return (
<AreaChart
  stacked
  labels={["Jan", "Feb", "Mar", "Apr", "May", "Jun"]}
  series={[
    { label: "Mobile", values: [42, 48, 51, 57, 63, 70] },
    { label: "Desktop", values: [35, 36, 38, 37, 40, 41] },
    { label: "Tablet", values: [8, 9, 9, 10, 11, 11] }
  ]}
/>
  );
}
