// Extracts the design hand-off's component prop contracts into a committed snapshot.
//
// The hand-off (the Claude Design "Canvas Design System" export) lives OUTSIDE this repo, so a
// parity check that read it directly could only run on a machine that happens to have the export
// unpacked. Snapshotting the contracts into `handoff-props.json` is what lets the guard run in CI
// and lets a drift show up as a reviewable diff rather than a silent pass.
//
// Usage:
//   bun tools/handoff-parity/extract.ts --from /path/to/canvas-react
//
// The hand-off's .d.ts files are deliberately flat: one `export interface <Name>Props { … }` per
// component with no `extends` chains, so a structural parse is enough and there is no need to pull
// TypeScript in here. (The CANVAS side does have extends chains; that resolution lives in
// tools/handoff-parity/compare.ts, which uses this snapshot as its expected surface.)

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const OUT = join(import.meta.dir, "handoff-props.json");

export interface HandoffProp {
  /** Declared type, verbatim and whitespace-collapsed. */
  type: string;
  /** False when the declaration carries `?`. */
  required: boolean;
  /** The JSDoc line above the prop, if any. Carried so the report can explain what a gap costs. */
  doc?: string;
}

export interface HandoffComponent {
  tier: string;
  props: Record<string, HandoffProp>;
}

/** Pull one `interface <name> { … }` body out of a source file, brace-balanced. */
function interfaceBody(src: string, name: string): string | null {
  const open = new RegExp(`interface\\s+${name}\\b[^{]*\\{`, "g").exec(src);
  if (!open) return null;
  let depth = 1;
  let i = open.index + open[0].length;
  const start = i;
  for (; i < src.length && depth > 0; i++) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}") depth--;
  }
  return src.slice(start, i - 1);
}

/**
 * Read the top-level members of an interface body. Nested object literals are skipped by brace
 * depth so a prop like `messages?: Partial<Record<"required" | …, string>>` contributes one entry
 * rather than one per union member.
 */
function members(body: string): Record<string, HandoffProp> {
  const out: Record<string, HandoffProp> = {};
  let depth = 0;
  let doc: string | undefined;
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (line.startsWith("/**")) doc = line.replace(/^\/\*+\s*|\s*\*+\/$/g, "").trim() || undefined;
    else if (line.startsWith("*") && !line.startsWith("*/") && doc !== undefined)
      doc = `${doc} ${line.replace(/^\*+\s*/, "").replace(/\s*\*+\/$/, "")}`.trim();

    if (depth === 0) {
      const m = line.match(/^["']?([a-zA-Z_][\w-]*)["']?(\?)?\s*:\s*(.+?);?\s*$/);
      if (m && !line.startsWith("*") && !line.startsWith("//")) {
        out[m[1]] = {
          type: m[3].replace(/;$/, "").replace(/\s+/g, " ").trim(),
          required: !m[2],
          ...(doc ? { doc: doc.replace(/\s*\*\/$/, "").trim() } : {}),
        };
        doc = undefined;
      }
    }
    depth += (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
    if (depth < 0) depth = 0;
    if (line.endsWith(";") && !line.startsWith("*")) doc = undefined;
  }
  return out;
}

const fromFlag = process.argv.indexOf("--from");
if (fromFlag === -1 || !process.argv[fromFlag + 1]) {
  console.error("usage: bun tools/handoff-parity/extract.ts --from <path-to-handoff-export>");
  process.exit(1);
}
const root = join(process.argv[fromFlag + 1], "components");

const components: Record<string, HandoffComponent> = {};
for (const tier of (await readdir(root, { withFileTypes: true })).filter((e) => e.isDirectory())) {
  for (const name of await readdir(join(root, tier.name))) {
    const file = join(root, tier.name, name, `${name}.d.ts`);
    let src: string;
    try {
      src = await readFile(file, "utf-8");
    } catch {
      continue; // not every folder carries a .d.ts
    }
    const body = interfaceBody(src, `${name}Props`);
    if (!body) continue;
    components[name] = { tier: tier.name, props: members(body) };
  }
}

const names = Object.keys(components).sort();
const snapshot = {
  note:
    "Generated by tools/handoff-parity/extract.ts. The design hand-off's component prop contracts, " +
    "snapshotted so scripts/check-handoff-parity.ts can run without the export present.",
  components: Object.fromEntries(names.map((n) => [n, components[n]])),
};

await writeFile(OUT, `${JSON.stringify(snapshot, null, 2)}\n`);
const propCount = names.reduce((a, n) => a + Object.keys(components[n].props).length, 0);
console.log(`Wrote ${OUT}`);
console.log(`  ${names.length} components, ${propCount} props`);
