/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/command/command.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Card, Command } = scope;
  return (
<Card flush>
  <Command embedded filtered defaultQuery="universal" groups={[
    { heading: "Guides", items: [
      { label: "Canvas", description: "A universal interface kit" }
    ] }
  ]} />
</Card>
  );
}
