// Checks the kit's public prop surface against the design hand-off's, and regenerates
// HANDOFF-PARITY.md.
//
// Why this exists: validate-tokens guards the TOKEN layer by value, but nothing guarded the
// COMPONENT layer, so a capability the hand-off specifies could go missing (or a hand-off revision
// could add one) with no signal at all. That is how `Field`, `DashboardGrid` and `ChartFrame` went
// unnoticed as absent.
//
// What it does NOT do: demand identical prop NAMES. Canvas is a React Native kit whose CLAUDE.md
// bans the string-enum props the hand-off uses freely (`size="lg"` is rejected in favour of
// `large`), and RN has no `onClick`. Those differences are intentional and are recorded, with a
// reason, in tools/handoff-parity/divergences.json. The build fails only on an UNCLASSIFIED
// difference — a real gap, or a hand-off prop nobody has adjudicated yet.

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { KIND_LABEL, MissingDistError, compareParity, distSources, isGap, readDivergences, readSnapshot, type Row } from "../tools/handoff-parity/compare.ts";

// The comparison itself (reading the built prop surface, resolving `extends`, looking every
// difference up in divergences.json, verifying redirects, finding dead records) lives in
// tools/handoff-parity/compare.ts, shared with the audit's facts. This script turns it into the
// report and the verdict.

const ROOT = join(import.meta.dir, "..");
const DIST = join(ROOT, "dist");
const REPORT = join(ROOT, "HANDOFF-PARITY.md");

const snapshot = readSnapshot(ROOT);
const divergences = readDivergences(ROOT);

let dist: string;
try {
  dist = distSources(DIST);
} catch (error) {
  if (!(error instanceof MissingDistError)) throw error;
  console.error("dist/ not found. Run `bun run build` first (CI builds before this check).");
  process.exit(1);
}

const { missingComponents, classified, unclassified, brokenRedirects, deadRecords, satisfied, handoffProps } = compareParity(snapshot, divergences, dist);

// ---------- report ----------

const settled = classified.filter((r) => !isGap(r.divergence!));
const openGaps = classified.filter((r) => isGap(r.divergence!));
const absentTracked = missingComponents.filter((c) => c.divergence);
const absentUntracked = missingComponents.filter((c) => !c.divergence);

const byComponent = (rows: Row[]): Map<string, Row[]> => {
  const m = new Map<string, Row[]>();
  for (const r of rows) {
    const list = m.get(r.component);
    if (list) list.push(r);
    else m.set(r.component, [r]);
  }
  return m;
};

const esc = (t: string): string => t.replace(/\|/g, "\\|");

const lines: string[] = [];
lines.push("# Hand-off parity");
lines.push("");
lines.push("<!-- Generated by scripts/check-handoff-parity.ts. Do not edit by hand: run `bun run check-parity`. -->");
lines.push("");
lines.push(
  "How this kit's public prop surface compares to the design hand-off's. Parity here means the same",
  "CAPABILITY, not the same prop name. Canvas is a React Native kit whose semantic-boolean prop rule",
  "rejects the string-enum props the hand-off uses freely (`size=\"lg\"` is spelled `large`), and React",
  "Native has no `onClick`. A difference is only a defect when it is a capability the kit cannot",
  "express.",
);
lines.push("");
lines.push(
  "Every difference is adjudicated in `tools/handoff-parity/divergences.json`. **Settled** ones are",
  "closed questions. **Open gaps** are real missing capabilities, acknowledged and tracked. The check",
  "fails on a difference recorded in neither place, so a hand-off revision surfaces loudly, and on a",
  "**broken redirect**: a settled record naming a Canvas prop that does not exist. That guard was",
  "added after three records (`Gauge.size`, `PieChart.size`, `Drawer.size`) were found pointing at",
  "`small`/`large` props their components had never had, which read as settled parity and sent",
  "documentation examples chasing props that silently do nothing.",
);
lines.push("");
lines.push(
  "It also fails on a **dead record**: one for a prop the kit now declares under the hand-off's own",
  "name, or for a component the kit now exports. A record is consulted only while the hand-off prop",
  "is ABSENT here, so shipping the capability makes its record unreadable, and every dead one found",
  "so far had gone false as well (`Tooltip.children` still said the Tooltip could not attach to a",
  "caller's node; `ActionPanel.children` and `Navbar.actions` denied slots their components had",
  "gained the day before). Those went unnoticed because closing a gap regenerates this report and",
  "the row simply disappears, leaving the record behind with nothing pointing at it.",
);
lines.push("");
lines.push(
  "**What this check cannot see.** It compares the prop SURFACE, not what a prop resolves to. Where",
  "a name exists on both sides it is counted satisfied even if the two render different metrics, so",
  "a scale or spacing drift passes silently. Those are recorded under Metric gaps below, from",
  "measurement rather than from this check. Redirect TARGETS are verified, so a settled record",
  "cannot name a prop that is absent, but nothing checks that the target is the RIGHT prop. It also",
  "compares against a committed snapshot of the",
  "hand-off, so it cannot tell you the snapshot itself has fallen behind the design source; refresh",
  "it with `tools/handoff-parity/extract.ts --from <export>`.",
);
lines.push("");
lines.push("## Summary");
lines.push("");
lines.push("| | |");
lines.push("|---|---|");
lines.push(`| Hand-off components | ${Object.keys(snapshot.components).length} |`);
lines.push(`| Present in the kit | ${Object.keys(snapshot.components).length - missingComponents.length} |`);
lines.push(`| Absent (tracked) | ${absentTracked.length} |`);
lines.push(`| Hand-off props compared | ${handoffProps} |`);
lines.push(`| Same name, present | ${satisfied} |`);
lines.push(`| Settled divergences | ${settled.length} |`);
lines.push(`| Open gaps (tracked) | ${openGaps.length} |`);
lines.push(`| Metric gaps (not detectable here) | ${Object.keys(divergences.metricGaps ?? {}).length} |`);
lines.push(`| **Unclassified** | **${unclassified.length + absentUntracked.length}** |`);
lines.push("");

if (missingComponents.length) {
  lines.push("## Components absent from the kit");
  lines.push("");
  lines.push("| Component | Tier | Hand-off props | Planned | Why it is missing |");
  lines.push("|---|---|---|---|---|");
  for (const c of missingComponents)
    lines.push(
      `| \`${c.name}\` | ${c.tier} | ${c.props} | ${c.divergence?.plannedIn ?? "**unrecorded**"} | ${c.divergence?.reason ?? "—"} |`,
    );
  lines.push("");
}

if (unclassified.length) {
  lines.push("## Unclassified differences");
  lines.push("");
  lines.push("Each is either a real capability gap or a difference nobody has adjudicated yet.");
  lines.push("Close it in the kit, or record it in `divergences.json` with the reason.");
  lines.push("");
  for (const [component, rows] of byComponent(unclassified)) {
    lines.push(`### \`${component}\``);
    lines.push("");
    lines.push("| Prop | Type | What it does in the hand-off |");
    lines.push("|---|---|---|");
    for (const r of rows) lines.push(`| \`${r.prop}\` | \`${esc(r.type)}\` | ${r.doc ?? "—"} |`);
    lines.push("");
  }
}

if (openGaps.length) {
  lines.push("## Open gaps");
  lines.push("");
  lines.push("Capabilities the hand-off specifies that the kit does not offer. Acknowledged, not settled.");
  lines.push("");
  lines.push("| Component | Prop | Planned | What it does in the hand-off |");
  lines.push("|---|---|---|---|");
  for (const r of openGaps)
    lines.push(`| \`${r.component}\` | \`${r.prop}\` | ${r.divergence!.plannedIn ?? "unscheduled"} | ${r.divergence!.reason} |`);
  lines.push("");
}

const metricGaps = Object.values(divergences.metricGaps ?? {});
if (metricGaps.length) {
  lines.push("## Metric gaps");
  lines.push("");
  lines.push(
    "Differences this check CANNOT see. It compares the prop surface, so when a prop exists on both",
    "sides it is reported as satisfied no matter what value it resolves to. These were found by",
    "measuring the rendered result and are recorded by hand.",
  );
  lines.push("");
  lines.push(
    "To find one: render the component's three-up in the docs, read the rendered element's own",
    "computed metrics rather than the source, and compare against a component you believe is",
    "correct as a control. A control matters more than it sounds \u2014 an AvatarMenu whose three rows",
    "all reported the web numbers only looked wrong beside a Dropdown whose three rows differed.",
    "Interactive state has to be driven first: a closed menu measures nothing.",
  );
  lines.push("");
  lines.push("| Component | Canvas | Hand-off | Planned | Why |");
  lines.push("|---|---|---|---|---|");
  for (const g of metricGaps)
    lines.push(`| \`${g.component}\` | ${g.canvas} | ${g.handoff} | ${g.plannedIn ?? "unscheduled"} | ${g.reason} |`);
  lines.push("");
}

if (settled.length) {
  lines.push("## Settled divergences");
  lines.push("");
  lines.push("Differences in spelling or shape where the kit carries the capability its own way.");
  lines.push("");
  lines.push("| Component | Hand-off prop | Kind | Canvas equivalent | Why |");
  lines.push("|---|---|---|---|---|");
  for (const r of settled) {
    const d = r.divergence!;
    const to = d.to ? (Array.isArray(d.to) ? d.to.map((t) => `\`${t}\``).join(", ") : `\`${d.to}\``) : "—";
    lines.push(`| \`${r.component}\` | \`${r.prop}\` | ${KIND_LABEL[d.kind]} | ${to} | ${d.reason} |`);
  }
  lines.push("");
}

const report = `${lines.join("\n")}\n`;

// --check regenerates nothing and instead asserts the committed report is current, the same
// contract docs:gen:check and raster:gen:check use. Without it a divergences.json edit could land
// with a stale HANDOFF-PARITY.md beside it and nothing would notice.
const checkOnly = process.argv.includes("--check");
let reportStale = false;
if (checkOnly) {
  let existing = "";
  try {
    existing = await readFile(REPORT, "utf-8");
  } catch {
    existing = "";
  }
  reportStale = existing !== report;
} else {
  await writeFile(REPORT, report);
}

// ---------- verdict ----------

console.log(
  `Hand-off parity: ${Object.keys(snapshot.components).length} components, ${handoffProps} props compared`,
);
console.log(`  present: ${satisfied}   settled divergences: ${settled.length}   open gaps: ${openGaps.length}`);
console.log(`  components absent from the kit: ${missingComponents.length} (${absentTracked.length} tracked)`);
console.log(checkOnly ? `Report checked: ${reportStale ? "STALE" : "current"}` : `Report written to ${REPORT}`);

const failures =
  unclassified.length + absentUntracked.length + brokenRedirects.length + deadRecords.length + (reportStale ? 1 : 0);
if (failures) {
  console.log("");
  for (const c of absentUntracked) console.log(`  UNRECORDED COMPONENT  ${c.name} (${c.tier})`);
  for (const r of unclassified) console.log(`  UNCLASSIFIED PROP     ${r.component}.${r.prop}: ${r.type}`);
  for (const b of brokenRedirects) console.log(`  BROKEN REDIRECT       ${b}`);
  for (const d of deadRecords) console.log(`  DEAD RECORD           ${d}`);
  if (reportStale) console.log(`  STALE REPORT          ${REPORT} is out of date; run \`bun run check-parity\`.`);
  console.log("");
  if (unclassified.length || absentUntracked.length)
    console.log("Close the gap in the kit, or record it in tools/handoff-parity/divergences.json.");
  if (brokenRedirects.length)
    console.log("A redirect names the prop that carries the capability in Canvas. Point it at a prop that exists, or reclassify the record as an open gap / intentional omission.");
  if (deadRecords.length)
    console.log("The kit closed that difference: delete the record from tools/handoff-parity/divergences.json, since nothing reads it and it still reads as adjudication.");
  process.exit(1);
}
console.log("Hand-off parity check passed.");
