/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/typography/typography.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Typography } = scope;
  return (
<Typography small>
  Read the <Typography small underline href="https://canvas.nannier.com">Canvas docs</Typography> for the full component list.
</Typography>
  );
}
