/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/scroll-view/scroll-view.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { tokens, Image, ScrollView, Typography } = scope;
  return (
<ScrollView style={{ height: 120, width: "100%", borderRadius: 10, borderWidth: 1, borderColor: tokens.border }} contentContainerStyle={{ padding: 12, gap: 8 }}>
  <Typography small>Deploy started</Typography>
  <Typography small>Dependencies restored from cache</Typography>
  <Typography small>Tests passed</Typography>
  <Typography small>Image pushed to the registry</Typography>
  <Typography small>Rollout reached half the fleet</Typography>
  <Typography small>Rollout complete</Typography>
</ScrollView>
  );
}
