/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/filter-panel/filter-panel.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { FilterPanel } = scope;
  return (
<FilterPanel
  groups={[
    { title: "Status", options: [
      { label: "Active", checked: true, count: "128" },
      { label: "Archived", count: "14" }
    ] },
    { title: "Region", options: [
      { label: "North America", count: "86" },
      { label: "Europe", count: "56" }
    ] }
  ]}
/>
  );
}
